# -*- coding: utf-8 -*-
"""PromptEngineeringlangchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OXY87r0y49dq4jWQUH5qA5tHwa6gRya-
"""

!pip install langchain langchain-groq langchain-community langchain-core --quiet

response=chain.invoke({"instruction":"draft a content for Toastmaster international speech for area contest"})

#template code to build the AI agents -zero shot prompting example

import os
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

os.environ["GROQ_API_KEY"]="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"

llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0)

prompt=PromptTemplate(
    input_variables=["instruction"],
    template="Follow the instruction and provide the output clearly:\n\nInstruction:{instruction}\n\nAnswer:"
)
parser=StrOutputParser()
chain = prompt | llm | parser

response=chain.invoke({
    "instruction" : "Translate 'Good evening, how are you?' to Tamil"})
print(response)

#template code to build the AI agents -zero shot prompting example

import os
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

os.environ["GROQ_API_KEY"]="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"

llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0)

prompt=PromptTemplate(
    input_variables=["instruction"],
    template="Follow the instruction and provide the output clearly:\n\nInstruction:{instruction}\n\nAnswer:"
)
parser=StrOutputParser()
chain = prompt | llm | parser

response = chain.invoke({
    "instruction": "Write a motivational Toastmasters speech introduction for an Area Contest"
})
print(response)

import os
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

os.environ["GROQ_API_KEY"]="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"

llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0)

prompt=PromptTemplate(
    input_variables=["instruction"],
    template="Follow the instruction and provide the output clearly:\n\nInstruction:{instruction}\n\nAnswer:"
)
parser=StrOutputParser()
chain = prompt | llm | parser

response = chain.invoke({
    "instruction": """
Example 1:
Topic: Confidence
Speech Opening:
Good evening fellow Toastmasters and guests. Confidence is not something we are born with; it is something we build one step at a time.

Example 2:
Topic: Leadership
Speech Opening:
Good evening everyone. Leadership is not about holding a position; it is about inspiring others to achieve a common goal.

Example 3:
Topic: Growth
Speech Opening:
Every challenge we face today has the potential to become tomorrow's success story.

Now write a Toastmasters International Area Contest speech opening for:

Topic: Learning to Say No at the Right Time
"""
})
print(response)

for one question genrate solution 4 different solution go with tree of thought chose best complexity and time and space optimcAL SOLUTION add in tiwilo

import os
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

os.environ["GROQ_API_KEY"]="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"

llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0)

prompt=PromptTemplate(
    input_variables=["instruction"],
    template="Follow the instruction and provide the output clearly:\n\nInstruction:{instruction}\n\nAnswer:"
)
parser=StrOutputParser()
chain = prompt | llm | parser



response = chain.invoke({
    "instruction": """
You are an expert competitive programmer.

Given a coding problem:

1. Generate 4 different approaches to solve the problem.
2. Explain each approach briefly.
3. Analyze Time Complexity and Space Complexity of each approach.
4. Compare all approaches.
5. Select the most optimal solution.
6. Explain why it is the best choice.
7. Generate the complete optimized code.
8. Include edge cases and test cases.

Problem:
Find the maximum element in an array.
"""
})
print(response)

!pip install twilio

from twilio.rest import Client

account_sid = "AC744fb9dceb3095765d917589a25c05cb"
auth_token = "e122fa4a8d999c827628a202467d84cc"

client = Client(account_sid, auth_token)

FROM = "your_twilio_phone_number"
TO = "recipient_phone_number"

# Generate response from LangChain

response = chain.invoke({
    "instruction": """
    You are an expert competitive programmer.

    Based on the problem:
    Find the maximum element in an array.

    Provide only the best solution and the optimized code for it.
    """
})

# Send response to WhatsApp

msg = client.messages.create(
    body=response,
    from_=FROM,
    to=TO
)

print("Message sent successfully!")
print("Message SID:", msg.sid)

#Twilio Sandbox
import os
from getpass import getpass    # to ensure that the data is not leak
from twilio.rest import Client

# --- Twilio credentials ---
TW_SID = os.environ.get('TWILIO_SID')
TW_TOKEN = os.environ.get('TWILIO_TOKEN')


if not TW_SID or not TW_TOKEN:
    print("Enter your Twilio Account SID and Auth Token:")
    TW_SID = getpass("Twilio SID: ")
    TW_TOKEN = getpass("Twilio Token: ")
    os.environ['TWILIO_SID'] = TW_SID
    os.environ['TWILIO_TOKEN'] = TW_TOKEN
#twilio whatsapp sandbox sender
FROM = 'whatsapp:+14155238886'

TO = input("Enter your WhatsApp number (e.g.. +91XXXXXXXXXX): ").strip()

if not TO.startswith('whatsapp'):
  TO = f'whatsapp:{TO}'

#inititalize twilio client
client = Client(TW_SID, TW_TOKEN)

msg=client.messages.create(
    body='Hello nandhini- test message!',
    from_=FROM,
    to=TO
)

print(' Message send successfully')
print('Message STD:',msg.sid)

# Install Required Packages
!pip install langchain langchain-groq langchain-core twilio

import os
from getpass import getpass

# LangChain Imports
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

# Twilio Import
from twilio.rest import Client

# -----------------------------------
# GROQ API KEY
# -----------------------------------

if "GROQ_API_KEY" not in os.environ:
    os.environ["GROQ_API_KEY"] = getpass("Enter GROQ API Key: ")

# -----------------------------------
# LLM
# -----------------------------------

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0
)

# -----------------------------------
# PROMPT TEMPLATE
# -----------------------------------

prompt = PromptTemplate(
    input_variables=["problem"],
    template="""
You are an expert competitive programmer.

For the given problem:

1. Generate 4 approaches.
2. Compare Time and Space Complexity.
3. Select the best approach.
4. Generate optimized Python code.
5. Include sample input and output.

Problem:
{problem}
"""
)

# -----------------------------------
# PARSER
# -----------------------------------

parser = StrOutputParser()

# -----------------------------------
# CHAIN
# -----------------------------------

chain = prompt | llm | parser

# -----------------------------------
# USER INPUT
# -----------------------------------

problem = input("Enter Coding Problem: ")

response = chain.invoke({
    "problem": problem
})

print("\n========================")
print("AI GENERATED SOLUTION")
print("========================\n")

print(response)

# -----------------------------------
# TWILIO CREDENTIALS
# -----------------------------------

TW_SID = os.environ.get("TWILIO_SID")
TW_TOKEN = os.environ.get("TWILIO_TOKEN")

if not TW_SID or not TW_TOKEN:
    TW_SID = getpass("Enter Twilio SID: ")
    TW_TOKEN = getpass("Enter Twilio Auth Token: ")

# -----------------------------------
# TWILIO CLIENT
# -----------------------------------

client = Client(TW_SID, TW_TOKEN)

# Sandbox Number
FROM = "whatsapp:+14155238886"

# Your WhatsApp Number
TO = input("Enter WhatsApp Number (+91XXXXXXXXXX): ").strip()

if not TO.startswith("whatsapp:"):
    TO = f"whatsapp:{TO}"

print("\nSending WhatsApp Message...")
print("TO:", TO)

# -----------------------------------
# SHORTEN MESSAGE
# -----------------------------------

whatsapp_message = f"""
Problem:
{problem}

Solution:
{response[:1200]}
"""

# -----------------------------------
# SEND MESSAGE
# -----------------------------------

msg = client.messages.create(
    body=whatsapp_message,
    from_=FROM,
    to=TO
)

print("\nMessage Request Submitted")
print("SID:", msg.sid)

# -----------------------------------
# CHECK STATUS
# -----------------------------------

message = client.messages(msg.sid).fetch()

print("\n===== MESSAGE DETAILS =====")
print("Status       :", message.status)
print("Error Code   :", message.error_code)
print("Error Message:", message.error_message)

if message.status in ["sent", "delivered", "queued"]:
    print("\n WhatsApp Message Sent Successfully!")
else:
    print("\n Message Delivery Failed")

from langchain_core.prompts import PromptTemplate

prompt = PromptTemplate(
    input_variables=["question"],
    template="""
You are an advanced reasoning assistant.

Step 1: Generate THREE different reasoning paths to solve the problem.

Step 2: Evaluate each path for correctness.

Step 3: Choose the best path.

Step 4: Provide the final answer.

Question: {question}

Return the answer in this format:

Reasoning Path 1:

Reasoning Path 2:

Reasoning Path 3:

Evaluation:

Best Path:

Final Answer:
"""
)

# Redefine the chain using the local prompt, and global llm and parser
chain = prompt | llm | parser

response = chain.invoke({
    "question": "Find the maximum element in an array"
})

print(response)

# Install Required Packages
# !pip install langchain langchain-groq langchain-core twilio
#all in one code learn this

import os
from getpass import getpass

# LangChain Imports
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

# Twilio Import
from twilio.rest import Client

# ======================================================
# STEP 1: GROQ API KEY
# ======================================================

if "GROQ_API_KEY" not in os.environ:
    os.environ["GROQ_API_KEY"] = getpass("Enter GROQ API Key: ")

# ======================================================
# STEP 2: LLM
# ======================================================

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0
)

# ======================================================
# STEP 3: TREE OF THOUGHTS PROMPT
# ======================================================

prompt = PromptTemplate(
    input_variables=["question"],
    template="""
You are an advanced reasoning assistant.

Step 1: Generate THREE different reasoning paths to solve the problem.

Step 2: Evaluate each path for correctness.

Step 3: Choose the best path.

Step 4: Provide the final answer.

Question: {question}

Return the answer in this format:

Reasoning Path 1:

Reasoning Path 2:

Reasoning Path 3:

Evaluation:

Best Path:

Final Answer:
"""
)

# ======================================================
# STEP 4: OUTPUT PARSER
# ======================================================

parser = StrOutputParser()

# ======================================================
# STEP 5: CHAIN
# ======================================================

chain = prompt | llm | parser

# ======================================================
# STEP 6: USER QUESTION
# ======================================================

question = input("Enter your question/problem: ")

response = chain.invoke({
    "question": question
})

print("\n==============================")
print("TREE OF THOUGHTS RESPONSE")
print("==============================\n")

print(response)

# ======================================================
# STEP 7: TWILIO CREDENTIALS
# ======================================================

TW_SID = os.environ.get("TWILIO_SID")
TW_TOKEN = os.environ.get("TWILIO_TOKEN")

if not TW_SID:
    TW_SID = getpass("Enter Twilio SID: ")

if not TW_TOKEN:
    TW_TOKEN = getpass("Enter Twilio Auth Token: ")

# ======================================================
# STEP 8: TWILIO CLIENT
# ======================================================

client = Client(TW_SID, TW_TOKEN)

# Twilio WhatsApp Sandbox Number
FROM = "whatsapp:+14155238886"

# Your WhatsApp Number
TO = input("Enter WhatsApp Number (+91XXXXXXXXXX): ").strip()

if not TO.startswith("whatsapp:"):
    TO = f"whatsapp:{TO}"

# ======================================================
# STEP 9: SEND TO WHATSAPP
# ======================================================

message_text = f"""
Tree of Thoughts Result

Question:
{question}

Result:
{response[:1200]}
"""

msg = client.messages.create(
    body=message_text,
    from_=FROM,
    to=TO
)

print("\nMessage Request Submitted")
print("SID:", msg.sid)

# ======================================================
# STEP 10: CHECK DELIVERY STATUS
# ======================================================

message = client.messages(msg.sid).fetch()

print("\n===== MESSAGE DETAILS =====")
print("Status       :", message.status)
print("Error Code   :", message.error_code)
print("Error Message:", message.error_message)

if message.status in ["queued", "sent", "delivered"]:
    print("\n✅ WhatsApp Message Sent Successfully!")
else:
    print("\n❌ Message Delivery Failed")

