# -*- coding: utf-8 -*-
"""DAY-1-PRACTICE QUESTIONS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jFuNhEMq0Q-8JOwDCxMrWeLXYdVa8ZCZ
"""

import pandas as pd

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv("student_dataset.csv")

display(df)

electronics_students = df[
    df["department"] == "ECE"
]

count_electronics = len(electronics_students)

print(
    f"Number of students from Electronics Department : {count_electronics}"
)

female_students = df[
    df["gender"] == "Female"
]

avg_attendance = female_students[
    "attendance_percentage"
].mean()

print(
    f"Average Attendance of Female Students : {avg_attendance:.2f}"
)

lowest_programming = df[
    df["programming_score"] ==
    df["programming_score"].min()
]

display(
    lowest_programming[
        ["name", "programming_score"]
    ]
)

students_above_80 = df[
    df["math_score"] > 80
]

count_students = len(students_above_80)

print(
    f"Number of students who scored above 80 in math : {count_students}"
)

high_attendance_students = df[
    df["attendance_percentage"] > 90
]

avg_total_score = high_attendance_students[
    "total_score"
].mean()

print(
    f"Average Total Score for Students with Attendance above 90% : {avg_total_score:.2f}"
)