# -*- coding: utf-8 -*-
"""day-1-miniproject-intern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJ2-KQ0q8DKQcngPh4OdHJt-WDM4omlA
"""

import pandas as pd

df = pd.read_csv("student_dataset.csv")

display(df)

print("=" * 60)
print("         STUDENT PERFORMANCE ANALYSIS")
print("=" * 60)

display(df)

total_students = len(df)

total_columns = len(df.columns)

unique_departments = df["department"].nunique()

print("\nDATASET OVERVIEW")
print("-" * 40)

print(f"Total Number of Students : {total_students}")

print(f"Total Number of Columns  : {total_columns}")

print(f"Unique Departments       : {unique_departments}")

department_count = df["department"].value_counts()

print("\nDEPARTMENT WISE ANALYSIS")
print("-" * 40)

display(department_count)

highest_math = df["math_score"].max()

lowest_math = df["math_score"].min()

avg_math = df["math_score"].mean()

avg_programming = df["programming_score"].mean()

avg_attendance = df["attendance_percentage"].mean()

print("\nSCORE ANALYSIS")
print("-" * 40)

print(f"Highest Math Score        : {highest_math}")

print(f"Lowest Math Score         : {lowest_math}")

print(f"Average Math Score        : {avg_math:.2f}")

print(f"Average Programming Score : {avg_programming:.2f}")

print(f"Average Attendance        : {avg_attendance:.2f}")

gender_avg = df.groupby("gender")["total_score"].mean()

print("\nGENDER WISE ANALYSIS")
print("-" * 40)

display(gender_avg)

top5 = df.sort_values(
    by="total_score",
    ascending=False
).head(5)

print("\nTOP 5 PERFORMERS")
print("-" * 40)

display(
    top5[
        ["name", "department", "total_score"]
    ]
)

low_attendance = df[
    df["attendance_percentage"] < 75
]

print("\nATTENDANCE ANALYSIS")
print("-" * 40)

if low_attendance.empty:

    print("All students have attendance above 75%")

else:

    display(
        low_attendance[
            ["name", "department", "attendance_percentage"]
        ]
    )

low_attendance = df[
    df["attendance_percentage"] < 75
]

print("\nATTENDANCE ANALYSIS")
print("-" * 40)

if low_attendance.empty:

    print("All students have attendance above 75%")

else:

    for index, row in low_attendance.iterrows():

        print(f"Name        : {row['name']}")

        print(f"Department  : {row['department']}")

        print(f"Attendance  : {row['attendance_percentage']}")

        print("-" * 30)