# -*- coding: utf-8 -*-
"""DAY2-MINIPROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1upRSOMbWLNZPToXT8GUYHjTP35Iz27oB
"""

cursor = conn.cursor()

cursor.execute("""
SELECT name FROM sqlite_master
WHERE type='table';
""")

tables = cursor.fetchall()

print(tables)

query1 = """
SELECT department,
       ROUND(AVG(math_score),2) AS avg_math
FROM student
GROUP BY department
ORDER BY avg_math DESC;
"""

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE students (
    id INTEGER PRIMARY KEY,
    name TEXT,
    gender TEXT,
    department TEXT,
    math_score INTEGER,
    science_score INTEGER,
    english_score INTEGER,
    attendance INTEGER
)
""")

conn.commit()

cursor.execute("""
INSERT INTO students
(name, gender, department, math_score, science_score, english_score, attendance)

VALUES
('Ananya Das','Female','Computer Science',95,92,94,90),
('Tanvi Mehta','Female','Mechanical',88,85,87,82),
('Akanksha Yadav','Female','Electronics',91,90,89,88),
('Arjun Nair','Male','Civil',78,80,79,76)
""")

conn.commit()

query1 = """
SELECT department,
       ROUND(AVG(math_score),2) AS avg_math
FROM students
GROUP BY department
ORDER BY avg_math DESC;
"""

chart1_data = pd.read_sql_query(query1, conn)

print(chart1_data)

query1 = """
SELECT department,
       ROUND(AVG(math_score),2) AS avg_math
FROM students
GROUP BY department
ORDER BY avg_math DESC;
"""

chart1_data = pd.read_sql_query(query1, conn)

# Figure size
fig, ax = plt.subplots(figsize=(9,5))

# Different colors for each bar
colors = ['skyblue', 'orange', 'green', 'purple']

# Bar chart
bars = ax.bar(
    chart1_data['department'],
    chart1_data['avg_math'],
    color=colors,
    edgecolor='black',
    linewidth=2
)

# Value labels on top
ax.bar_label(
    bars,
    fmt='%.1f',
    padding=3,
    fontsize=10,
    fontweight='bold',
    color='black'
)

# Title
ax.set_title(
    "Avg Math Score by Department",
    fontsize=15,
    fontweight='bold'
)

# Axis labels
ax.set_xlabel(
    "Department",
    fontsize=12,
    fontweight='bold'
)

ax.set_ylabel(
    "Average Score",
    fontsize=12,
    fontweight='bold'
)

# Grid style
ax.grid(
    axis='y',
    linestyle='--',
    alpha=0.4
)

# Rotate labels
plt.xticks(rotation=10, fontsize=10)
plt.yticks(fontsize=10)

# Background color
ax.set_facecolor('#f5f5f5')

plt.show()

query2 = """
SELECT department,
       COUNT(*) AS student_count
FROM students
GROUP BY department;
"""

chart2_data = pd.read_sql_query(query2, conn)

# Figure size
fig, ax = plt.subplots(figsize=(8,8))

# Colors for pie chart
colors = ['skyblue', 'orange', 'limegreen', 'violet']

# Explode effect
explode = (0.05, 0.05, 0.05, 0.05)

# Pie Chart
wedges, texts, autotexts = ax.pie(
    chart2_data['student_count'],
    labels=chart2_data['department'],
    colors=colors,
    autopct='%1.1f%%',
    startangle=90,
    explode=explode,
    shadow=True,
    wedgeprops={
        'edgecolor': 'black',
        'linewidth': 2
    },
    textprops={
        'fontsize': 11,
        'fontweight': 'bold'
    }
)

# Title
ax.set_title(
    "Students per Department",
    fontsize=16,
    fontweight='bold'
)

plt.show()

query3 = """
SELECT name,
       (math_score + science_score + english_score + attendance) AS total_score
FROM students
ORDER BY total_score DESC
LIMIT 8;
"""

chart3_data = pd.read_sql_query(query3, conn)

# Figure size
fig, ax = plt.subplots(figsize=(11,6))

# Colors
colors = [
    'skyblue',
    'orange',
    'limegreen',
    'violet',
    'gold',
    'cyan',
    'pink',
    'salmon'
]

# Horizontal bar chart
bars = ax.barh(
    chart3_data['name'],
    chart3_data['total_score'],
    color=colors,
    edgecolor='black',
    linewidth=2
)

# Highest score on top
ax.invert_yaxis()

# Labels on bars
ax.bar_label(
    bars,
    padding=5,
    fontsize=10,
    fontweight='bold'
)

# Title
ax.set_title(
    "Top 8 Students — Total Score",
    fontsize=16,
    fontweight='bold'
)

# Axis labels
ax.set_xlabel(
    "Total Score",
    fontsize=12,
    fontweight='bold'
)

ax.set_ylabel(
    "Student Names",
    fontsize=12,
    fontweight='bold'
)

# Grid
ax.grid(
    axis='x',
    linestyle='--',
    alpha=0.4
)

# Background color
ax.set_facecolor('#f5f5f5')

plt.xticks(fontsize=10)
plt.yticks(fontsize=10)

plt.show()

query4 = """
SELECT gender,
       ROUND(AVG(attendance),2) AS avg_attendance
FROM students
GROUP BY gender;
"""

chart4_data = pd.read_sql_query(query4, conn)

# Figure size
fig, ax = plt.subplots(figsize=(7,5))

# Colors
colors = ['deeppink', 'dodgerblue']

# Bar chart
bars = ax.bar(
    chart4_data['gender'],
    chart4_data['avg_attendance'],
    color=colors,
    edgecolor='black',
    linewidth=2
)

# Labels on bars
ax.bar_label(
    bars,
    fmt='%.1f%%',
    padding=3,
    fontsize=11,
    fontweight='bold'
)

# Title
ax.set_title(
    "Avg Attendance by Gender",
    fontsize=15,
    fontweight='bold'
)

# Axis labels
ax.set_xlabel(
    "Gender",
    fontsize=12,
    fontweight='bold'
)

ax.set_ylabel(
    "Attendance %",
    fontsize=12,
    fontweight='bold'
)

# Grid
ax.grid(
    axis='y',
    linestyle='--',
    alpha=0.4
)

# Background color
ax.set_facecolor('#f5f5f5')

plt.xticks(fontsize=11)
plt.yticks(fontsize=10)

plt.show()

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# ================= DATABASE CONNECTION =================
conn = sqlite3.connect("student_database.db")

# ================= PANEL 1 =================
# Avg Math Score by Department

query1 = """
SELECT department,
       ROUND(AVG(math_score),2) AS avg_math
FROM students
GROUP BY department
ORDER BY avg_math DESC;
"""

chart1_data = pd.read_sql_query(query1, conn)

# ================= PANEL 2 =================
# Student Count by Department

query2 = """
SELECT department,
       COUNT(*) AS student_count
FROM students
GROUP BY department;
"""

chart2_data = pd.read_sql_query(query2, conn)

# ================= PANEL 3 =================
# Top 8 Students by Total Score

query3 = """
SELECT name,
       (math_score + science_score + english_score + attendance) AS total_score
FROM students
ORDER BY total_score DESC
LIMIT 8;
"""

chart3_data = pd.read_sql_query(query3, conn)

# ================= PANEL 4 =================
# Gender-wise Average Attendance

query4 = """
SELECT gender,
       ROUND(AVG(attendance),2) AS avg_attendance
FROM students
GROUP BY gender;
"""

chart4_data = pd.read_sql_query(query4, conn)

# ======================================================
# CREATE DASHBOARD
# ======================================================

fig, axs = plt.subplots(2, 2, figsize=(16,10))

# ======================================================
# PANEL 1 — BAR CHART
# ======================================================

colors1 = ['skyblue', 'orange', 'limegreen', 'violet']

bars1 = axs[0,0].bar(
    chart1_data['department'],
    chart1_data['avg_math'],
    color=colors1,
    edgecolor='black',
    linewidth=2
)

axs[0,0].bar_label(
    bars1,
    padding=3,
    fontsize=9,
    fontweight='bold'
)

axs[0,0].set_title(
    "Avg Math Score by Department",
    fontsize=14,
    fontweight='bold'
)

axs[0,0].set_xlabel("Department")
axs[0,0].set_ylabel("Average Score")

axs[0,0].grid(axis='y', linestyle='--', alpha=0.4)

# ======================================================
# PANEL 2 — PIE CHART
# ======================================================

colors2 = ['gold', 'cyan', 'lightgreen', 'pink']

explode = (0.05, 0.05, 0.05, 0.05)

axs[0,1].pie(
    chart2_data['student_count'],
    labels=chart2_data['department'],
    colors=colors2,
    autopct='%1.1f%%',
    startangle=90,
    explode=explode,
    shadow=True,
    wedgeprops={
        'edgecolor':'black',
        'linewidth':2
    },
    textprops={
        'fontsize':10,
        'fontweight':'bold'
    }
)

axs[0,1].set_title(
    "Students per Department",
    fontsize=14,
    fontweight='bold'
)

# ======================================================
# PANEL 3 — HORIZONTAL BAR CHART
# ======================================================

colors3 = [
    'red',
    'orange',
    'gold',
    'green',
    'blue',
    'purple',
    'pink',
    'brown'
]

bars3 = axs[1,0].barh(
    chart3_data['name'],
    chart3_data['total_score'],
    color=colors3,
    edgecolor='black',
    linewidth=2
)

axs[1,0].invert_yaxis()

axs[1,0].bar_label(
    bars3,
    padding=5,
    fontsize=9,
    fontweight='bold'
)

axs[1,0].set_title(
    "Top 8 Students — Total Score",
    fontsize=14,
    fontweight='bold'
)

axs[1,0].set_xlabel("Total Score")
axs[1,0].set_ylabel("Student Names")

axs[1,0].grid(axis='x', linestyle='--', alpha=0.4)

# ======================================================
# PANEL 4 — GENDER ATTENDANCE BAR CHART
# ======================================================

colors4 = ['deeppink', 'dodgerblue']

bars4 = axs[1,1].bar(
    chart4_data['gender'],
    chart4_data['avg_attendance'],
    color=colors4,
    edgecolor='black',
    linewidth=2
)

axs[1,1].bar_label(
    bars4,
    fmt='%.1f%%',
    padding=3,
    fontsize=10,
    fontweight='bold'
)

axs[1,1].set_title(
    "Avg Attendance by Gender",
    fontsize=14,
    fontweight='bold'
)

axs[1,1].set_xlabel("Gender")
axs[1,1].set_ylabel("Attendance %")

axs[1,1].grid(axis='y', linestyle='--', alpha=0.4)

# ======================================================
# MAIN DASHBOARD TITLE
# ======================================================

fig.suptitle(
    "Student Performance Dashboard",
    fontsize=20,
    fontweight='bold'
)

# Space adjustment
plt.tight_layout()

# Show dashboard
plt.show()

