# -*- coding: utf-8 -*-
"""DAY2-Practice Questions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fNoBJFfweEtLoGBMzVNAFu-hXWc1Nwpy
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import sqlite3
import matplotlib.pyplot as plt

df = pd.read_csv("student_performance.csv")

print(df.head())

conn = sqlite3.connect("student_database.db")

df.to_sql(
    "students",
    conn,
    if_exists="replace",
    index=False
)

print("Dataset Imported Successfully")

query = "SELECT * FROM students"

result = pd.read_sql_query(query, conn)

print(result.head())

query1 = """
SELECT department,
       ROUND(AVG(math_score),2) AS avg_math
FROM students
GROUP BY department
ORDER BY avg_math DESC;
"""

chart1_data = pd.read_sql_query(query1, conn)

print(chart1_data)

fig, ax = plt.subplots(figsize=(8,5))

bars = ax.bar(
    chart1_data['department'],
    chart1_data['avg_math'],
    color=['skyblue','orange','green','purple']
)

ax.bar_label(bars)

ax.set_title("Avg Math Score by Department")

plt.show()

query_where = """
SELECT *
FROM students
WHERE attendance_percentage > 85;
"""

result_where = pd.read_sql_query(query_where, conn)

print(result_where)

query_having = """
SELECT department,
       ROUND(AVG(attendance_percentage),2) AS avg_attendance
FROM students
GROUP BY department
HAVING AVG(attendance_percentage) > 85;
"""

result_having = pd.read_sql_query(query_having, conn)

print(result_having)

query_q3 = """
SELECT department,
       ROUND(AVG(attendance_percentage),2) AS avg_attendance
FROM students
GROUP BY department
HAVING AVG(attendance_percentage) > 85;
"""

result_q3 = pd.read_sql_query(query_q3, conn)

print(result_q3)

query = """
SELECT *
FROM students;
"""

df_result = pd.read_sql_query(query, conn)

print(df_result)

query_q5 = """
SELECT department,
       ROUND(AVG(programming_score),2) AS avg_programming
FROM students
GROUP BY department
ORDER BY avg_programming DESC;
"""

chart_q5 = pd.read_sql_query(query_q5, conn)


fig, ax = plt.subplots(figsize=(9,5))


colors = ['skyblue', 'orange', 'limegreen', 'violet']


bars = ax.bar(
    chart_q5['department'],
    chart_q5['avg_programming'],
    color=colors,
    edgecolor='black',
    linewidth=2
)


ax.bar_label(
    bars,
    fmt='%.1f',
    padding=3,
    fontsize=10,
    fontweight='bold'
)


ax.set_title(
    "Average Programming Score by Department",
    fontsize=15,
    fontweight='bold'
)


ax.set_xlabel(
    "Department",
    fontsize=12,
    fontweight='bold'
)

ax.set_ylabel(
    "Average Programming Score",
    fontsize=12,
    fontweight='bold'
)


ax.grid(
    axis='y',
    linestyle='--',
    alpha=0.4
)


ax.set_facecolor('#f5f5f5')


plt.xticks(rotation=10)

plt.show()

