# -*- coding: utf-8 -*-
"""DAY9-INTERN-TEXT-TO-SQL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQ4UAj2Hy2SF63lmeAy0IvFN0IQqhsmh
"""

!pip install groq -q
print("Libraries installed sucessfully")

#impor all libraries
import sqlite3
import pandas as pd
import os

from groq import Groq
import re

print("All libraries imported successfully ")

#initilizing the groq sql
import os
os.environ["GROQ_API_KEY"]=""
Client=Groq(api_key=os.environ["GROQ_API_KEY"])
MODEL="llama-3.1-8b-instant"
print("Groq client intialized successfully")
print(f"Using model:{MODEL}")

import io
csv_data = """student_id,name,age,gender,subject,marks,attendance,grade
1,Aarav Sharma,20,Male,Mathematics,88,92,A
2,Priya Patel,21,Female,Science,76,85,B
3,Rohan Mehta,20,Male,Programming,95,98,A+
4,Sneha Iyer,22,Female,Mathematics,62,78,C
5,Arjun Nair,21,Male,Programming,91,94,A+
6,Divya Krishnan,20,Female,Science,83,88,A
7,Karan Singh,22,Male,Mathematics,74,81,B
8,Ananya Gupta,21,Female,Programming,89,96,A
9,Vikram Reddy,20,Male,Science,70,79,B
10,Pooja Sharma,22,Female,Mathematics,55,72,D
11,Aditya Kumar,21,Male,Programming,97,99,A+
12,Meera Nambiar,20,Female,Science,81,87,A
13,Rahul Desai,22,Male,Mathematics,68,80,C
14,Kavitha Rajan,21,Female,Programming,86,93,A
15,Nikhil Verma,20,Male,Science,77,84,B
16,Swathi Pillai,22,Female,Mathematics,90,95,A+
17,Manish Joshi,21,Male,Programming,73,82,B
18,Lavanya Menon,20,Female,Science,66,76,C
19,Suresh Babu,22,Male,Mathematics,82,89,A
20,Anjali Singh,21,Female,Programming,94,97,A+
21,Deepak Nair,20,Male,Science,79,86,B
22,Rekha Sharma,22,Female,Mathematics,58,73,D
23,Sanjay Patel,21,Male,Programming,88,91,A
24,Usha Iyer,20,Female,Science,84,90,A
25,Vijay Kumar,22,Male,Mathematics,71,83,B
26,Nandita Rao,21,Female,Programming,92,96,A+
27,Ashok Reddy,20,Male,Science,65,77,C
28,Sunita Gupta,22,Female,Mathematics,87,93,A
29,Ravi Krishnan,21,Male,Programming,78,88,B
30,Bhavna Mehta,20,Female,Science,93,98,A+"""

df=pd.read_csv(io.StringIO(csv_data))
#df.to_csv("student_data.csv",index=False)
df=pd.read_csv(io.StringIO(csv_data))
print(f"Dataset loaded: {len(df)} rows, {len(df.columns)} columns")
print("\nFirst 5 rows")
df.head()

#Creating the Sqllite dataframe and loading data
conn=sqlite3.connect("college.db")
df.to_sql("students",conn,if_exists="replace",index=False)
print("Data created:college.db")
print("Table'students'created with 30 student records")
test_df=pd.read_sql_query("SELECT * FROM students",conn)
test_df=pd.read_sql_query("SELECT COUNT(*) as total_rows FROM students", conn)
print(f"\nVerification : {test_df['total_rows'][0]} rows in database")
df.head()

#Creating the Sqllite dataframe and loading data
conn=sqlite3.connect("college.db")
df.to_sql("students",conn,if_exists="replace",index=False)
print("Data created:college.db")
print("Table'students'created with 30 student records")
test_df=pd.read_sql_query("SELECT * FROM students",conn)
test_df=pd.read_sql_query("SELECT COUNT(*) as total_rows FROM students", conn)
print(f"\nVerification : {test_df['total_rows'][0]} rows in database")
df.tail()

#Creating the Sqllite dataframe and loading data
conn=sqlite3.connect("college.db")
df.to_sql("students",conn,if_exists="replace",index=False)
print("Data created:college.db")
print("Table'students'created with 30 student records")
test_df=pd.read_sql_query("SELECT * FROM students",conn)
test_df=pd.read_sql_query("SELECT COUNT(*) as total_rows FROM students", conn)
print(f"\nVerification : {test_df['total_rows'][0]} rows in database")

#understanding the schemaaaa

def get_schema(conn, table_name="students"):
  cursor=conn.cursor()
  cursor.execute(f"PRAGMA table_info({table_name})")
  columns = cursor.fetchall()

  schema_lines=[f"Table: {table_name}"]
  schema_lines.append("Columns: ")

  for col in columns:
    schema_lines.append(f" - {col[1]} ({col[2]})")

  cursor.execute(f"SELECT * FROM {table_name} LIMIT 3")
  sample_rows=cursor.fetchall()
  schema_lines.append("\nSample rows(first 3):")

  for row in sample_rows:
    schema_lines.append(f" {row}")

  return "\n".join(schema_lines)

schema=get_schema(conn)
print(schema)

"""**Writing the sql generation function**"""

def generate_sql(user_question, schema_text, client, model):
  system_prompt = f"""You are an expert SQL assistant.
You are connected to a SQLite database with the following structure:


{schema_text}


Rules you must follow:
1. Generate ONLY a valid SQLite SQL query.
2. Do not include any explanation or text — only the SQL query.
3. Do not use markdown code blocks. Return the raw SQL only.
4. The table name is: students
5. Only use column names that exist in the schema above.
6. Use single quotes for string values in WHERE clauses (example: WHERE subject = 'Programming').
7. If the user asks for top N, use ORDER BY marks DESC LIMIT N.
"""

  response=client.chat.completions.create(
    model=model,
    messages=[
      {"role": "system","content": system_prompt},
      { "role": "user", "content": user_question}
    ],
    temperature=0.0
  )
  sql_query=response.choices[0].message.content.strip()
  return sql_query

question="Show me all male students"
print(f"Question: {question}")
print("\nGenerating SQL..")

sql=generate_sql(question, schema, Client, MODEL)
print(f"\nGenerated SQL: {sql}")

def execute_sql(sql_query, conn):
  clean_sql = sql_query.strip()

  clean_sql=re.sub(r'```sql\s*', '', clean_sql)
  clean_sql=re.sub(r'```\s*', '', clean_sql)
  clean_sql=clean_sql.strip()

  try:
    result_df=pd.read_sql_query(clean_sql, conn)
    return result_df,None
  except Exception as e:
        return None,str(e)

print(f"Executing SQL: {sql}")
result,error=execute_sql(sql, conn)

if error:
  print(f"Error executing SQL: {error}")
else:
  print(f"Result: {len(result)} rows")
  print(result)

def text_to_sql(user_question, conn, client, model, verbose=True):


    print('User Question:', user_question)


    if verbose:
        print('Generating schema...')


    schema_text = get_schema(conn)


    if verbose:
        print('Schema loaded successfully.')


    if verbose:
        print('Generating SQL...')


    generated_sql = generate_sql(
        user_question,
        schema_text,
        client,
        model
    )


    if verbose:
        print('Generated SQL:')
        print(generated_sql)


    if verbose:
        print('Executing SQL...')


    result_df, error = execute_sql(generated_sql, conn)


    if error:
        print('Error:', error)
        return None, generated_sql


    if verbose:
        print('Results:')
        print(result_df.to_string(index=False))


    return result_df, generated_sql

def text_to_sql_agent(user_question, conn, client, model, verbose=True):
  print("="*60)

  print(f"USER QUESTION: {user_question}")
  print("="*60)

  if verbose:
    print("\n[STEP 1] Reading database schema...")

  schema_text=get_schema(conn)

  if verbose:
    print("Schema loaded successfully")

  if verbose:
    print("\n[STEP 2] Generating SQL query with Groq LLM....")

  generated_sql = generate_sql(user_question, schema_text, client, model)

  if verbose:
    print(f"Generated SQL:\n {generated_sql}")

  if verbose:
    print("\n[STEP 3] Executing generated SQL on the database...")

  result_df,error=execute_sql(generated_sql, conn)

  if error:
    print(f"SQL Error executing SQL: {error}")
    return None, generated_sql

  if verbose:
    print(f"\n[STEP 4] Query returned {len(result_df)}row(s) ")
    print("\n RESULTS:")
    print("="*40)
    print(result_df.to_string(index=False))
    print("="*60)

  return result_df, generated_sql

# Example usage (moved outside the function definition)
result, sql_used = text_to_sql_agent(
    "Show me all female students",
    conn,
    Client,
    MODEL,
)

import pandas as pd

# Convert Tanglish/Tamil-English query into proper English
def normalize_question(user_question, client, model):
    prompt = f"""
You are a translator for database queries.

Convert the following user query into clear English.

Examples:
"female students ah kaatu" -> "Show all female students"
"male students count sollu" -> "Count all male students"
"computer science la iruka students" -> "Show all students in Computer Science department"
"CS department students count" -> "Count students in Computer Science department"

User Query:
{user_question}

Return ONLY the English query.
"""

    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "user", "content": prompt}
        ],
        temperature=0
    )

    return response.choices[0].message.content.strip()


def text_to_sql_agent(user_question, conn, client, model, verbose=True):

    print("=" * 60)
    print(f"USER QUESTION: {user_question}")
    print("=" * 60)

    # STEP 0: Convert Tanglish to English
    if verbose:
        print("\n[STEP 0] Understanding user query...")

    normalized_question = normalize_question(
        user_question,
        client,
        model
    )

    if verbose:
        print(f"Interpreted Query: {normalized_question}")

    # STEP 1
    if verbose:
        print("\n[STEP 1] Reading database schema...")

    schema_text = get_schema(conn)

    if verbose:
        print("Schema loaded successfully")

    # STEP 2
    if verbose:
        print("\n[STEP 2] Generating SQL query with Groq LLM...")

    generated_sql = generate_sql(
        normalized_question,
        schema_text,
        client,
        model
    )

    if verbose:
        print(f"\nGenerated SQL:\n{generated_sql}")

    # STEP 3
    if verbose:
        print("\n[STEP 3] Executing generated SQL on database...")

    result_df, error = execute_sql(
        generated_sql,
        conn
    )

    if error:
        print(f"\nSQL Error: {error}")
        return None, generated_sql

    # STEP 4
    if verbose:
        print(f"\n[STEP 4] Query returned {len(result_df)} row(s)")
        print("\nRESULTS:")
        print("=" * 40)
        print(result_df.to_string(index=False))
        print("=" * 40)

    return result_df, generated_sql


# Example Queries

result, sql_used = text_to_sql_agent(
    "female students ah kaatu",
    conn,
    Client,
    MODEL
)

result, sql_used = text_to_sql_agent(
    "computer science la iruka students",
    conn,
    Client,
    MODEL
)

result, sql_used = text_to_sql_agent(
    "male students count sollu",
    conn,
    Client,
    MODEL
)

import os
os.environ['GROQ_API_KEY']=""

pip install gradio langchain-groq langchain-core

# Install Required Libraries
# !pip install gradio langchain-groq langchain-core

import os
import gradio as gr
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

def generate_captions(
    groq_api_key,
    platform,
    content_type,
    tone,
    description,
    length,
    hashtags,
    emoji,
    num_captions,
    max_tokens
):
    try:
        # Set API Key
        os.environ["GROQ_API_KEY"] = ""

        # LLM
        llm = ChatGroq(
            model="llama-3.3-70b-versatile",
            temperature=0.7,
            max_tokens=int(max_tokens)
        )

        # Prompt Template
        prompt = PromptTemplate(
            input_variables=[
                "platform",
                "content_type",
                "tone",
                "description",
                "length",
                "hashtags",
                "emoji",
                "num_captions"
            ],
            template="""
You are an expert social media content creator.

Generate {num_captions} DIFFERENT caption options.

User Preferences:
Platform: {platform}
Content Type: {content_type}
Tone: {tone}
Description: {description}
Caption Length: {length}
Include Hashtags: {hashtags}
Include Emojis: {emoji}

Platform Guidelines:
- Instagram → trendy, engaging
- LinkedIn → professional
- WhatsApp → short and impactful
- Facebook → conversational
- X/Twitter → concise and attention-grabbing
- GitHub → technical and developer-focused

Requirements:
1. Every caption must be different.
2. Use the requested tone.
3. Follow the requested length.
4. Include emojis only if requested.
5. Include hashtags only if requested.
6. Number each caption clearly.
7. Make captions creative and high quality.

Output Format:

Caption 1:
...

Caption 2:
...

Caption 3:
...
"""
        )

        parser = StrOutputParser()

        chain = prompt | llm | parser

        response = chain.invoke({
            "platform": platform,
            "content_type": content_type,
            "tone": tone,
            "description": description,
            "length": length,
            "hashtags": hashtags,
            "emoji": emoji,
            "num_captions": num_captions
        })

        return response

    except Exception as e:
        return f"Error: {str(e)}"


# Gradio Interface
with gr.Blocks(title="AI Caption Generator") as demo:

    gr.Markdown("# AI Social Media Caption Generator")
    gr.Markdown("Generate captions using Groq + LangChain")

    groq_api_key = gr.Textbox(
        label="Groq API Key",
        type="password"
    )

    platform = gr.Radio(
        ["Instagram", "LinkedIn", "WhatsApp", "Facebook", "X", "GitHub"],
        label="Select Platform"
    )

    content_type = gr.Radio(
        ["Photo", "Video", "Reel", "Story", "Post"],
        label="Content Type"
    )

    tone = gr.Dropdown(
        ["Funny", "Motivational", "Professional", "Sad", "Emotional"],
        label="Tone"
    )

    description = gr.Textbox(
        label="Describe your content",
        lines=4
    )

    length = gr.Radio(
        ["Short", "Medium", "Long"],
        label="Caption Length"
    )

    hashtags = gr.Radio(
        ["Yes", "No"],
        label="Include Hashtags?"
    )

    emoji = gr.Radio(
        ["Yes", "No"],
        label="Include Emojis?"
    )

    num_captions = gr.Slider(
        minimum=1,
        maximum=10,
        value=3,
        step=1,
        label="Number of Captions"
    )

    max_tokens = gr.Slider(
        minimum=100,
        maximum=2000,
        value=500,
        step=50,
        label="Maximum Tokens"
    )

    generate_btn = gr.Button("Generate Captions")

    output = gr.Textbox(
        label="Generated Captions",
        lines=20
    )

    generate_btn.click(
        fn=generate_captions,
        inputs=[
            groq_api_key,
            platform,
            content_type,
            tone,
            description,
            length,
            hashtags,
            emoji,
            num_captions,
            max_tokens
        ],
        outputs=output
    )

demo.launch()

!pip install ipywidgets

"""**opens GitHub from a button**"""

from IPython.display import display, HTML

display(HTML("""
<h3>Select Platform</h3>

<input type="radio" name="platform" value="Instagram" checked> Instagram<br>
<input type="radio" name="platform" value="LinkedIn"> LinkedIn<br>
<input type="radio" name="platform" value="GitHub"> GitHub<br>
<input type="radio" name="platform" value="X"> X<br><br>

<button onclick="
let selected = document.querySelector('input[name=platform]:checked').value;

if(selected === 'GitHub'){
    window.open('https://github.com/Nandhinis019', '_blank');
}
else{
    alert('You selected: ' + selected);
}
">
Submit
</button>
"""))

