# -*- coding: utf-8 -*-
"""DAY8-INTERN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/189YOHwQw0eFD3yyeFY4k6G-e3OamsBnH
"""

!pip install sentence-transformers chromadb groq pandas -q

import pandas as pd
import chromadb
from sentence_transformers import SentenceTransformer
from groq import Groq

import os
print("All Libraries imported successfully")
print("Ready to build a RAG system.")

GROQ_API_KEY=""
os.environ["GROQ_API_KEY"]=GROQ_API_KEY
groq_Cilent=Groq(api_key=GROQ_API_KEY)
print("Groq API cilent initialized")

from google.colab import files
import pandas as pd

# Upload file
uploaded = files.upload()


df = pd.read_csv('college_notes.csv')


print("First 3 Rows:")
print(df.head(3))


print("\nLast 3 Rows:")
print(df.tail(3))

print("Subjects in the dataset:")
print(df['subject'].value_counts())

print("\nSamples of topics:")
print(df[['note_id','subject','topic']].to_string(index=False))
print("\nLength of content (number of characters) for each note:")
df['content_length']=df['content'].apply(len)
print(df[['topic','content_length']].to_string(index=False))

documents=df['content'].tolist()
ids=[f"note_{row['note_id']}" for row in df.to_dict('records')]
metadatas = [
    {"subject" : row['subject'], "topic" : row['topic']}
    for row in df.to_dict('records')
]
print(f"Total chunks prepared : {len(documents)}")
print(f"Last doucment ID : {ids[14]}")
print(f"Last metadata : {metadatas[14]}")
print(f"First 100 chars of doc: {documents[14][:100]}...")

#sentence transformer for the embeddings
#converting text into an numerical values

embedding_model= SentenceTransformer('all-MiniLM-L6-v2')
print("\nEmbedding model loaded successfully")

test_embedding=embedding_model.encode("This is a test sentence.")

print(f"Test embedding shape: {test_embedding.shape}")
print(f"First 5 values of test embedding: {test_embedding[:5]}")

#to store we use the chroma db

chroma_client = chromadb.Client()
collection = chroma_client.get_or_create_collection(name="college_notes.csv")

print("ChromaDB client created")
print(f"Collection name: college_notes_rag")
print(f"Documents in collection so far: {collection.count()}")

print("Genrating embeddings for all 15 notes")
embeddings=embedding_model.encode(documents,show_progress_bar=True)
print("Embeddings shape:",embeddings.shape)
embeddings_list=embeddings.tolist()
collection.add(
    documents=documents,
    ids=ids,
    metadatas=metadatas,
    embeddings=embeddings_list
)

print("Generating embeddings for all 15 notes...")
print("This may take 15-30 seconds...")
embeddings=embedding_model.encode(documents,show_progress_bar=True)
print(f"\nEmbedding Matrix Shape: {embeddings.shape}")
embeddings_list=embeddings.tolist()
collection.add(
    documents=documents,
    metadatas=metadatas,
    ids=ids,
    embeddings=embeddings_list
)
print(f"Documents in collection so far: {collection.count()}")

def retrieve_revlevant_chuncks(question,top_k=3):
  """
  Given a user question,retrieve the most relevant document chuncks for
  paramet
  """
  question_embedding=embedding_model.encode(question).tolist()
  results = collection.query(
      query_embeddings=question_embedding,
      n_results=top_k
  )
  return results
print("Retrieval function is defined successfully")

test_question ="what is ETL and how doest it work in data engineering?"
print(f"Test Question:{test_question}")
print("="*60)
results=retrieve_revlevant_chuncks(test_question)
print("\n Top 3 retrieve_chunks:")
print("="*60)
for i,(doc,dist,meta) in enumerate(zip(
    results['documents'][0],
    results['distances'][0],
    results['metadatas'][0],
)):

 print(f"\nResult:{i+1}:")
 print(f"Subject:{meta['subject']}")
 print(f"Topic: {meta['topic']}")
 print(f"Distance:{dist}")
 print(f"Content:{doc[:100]}...")

def build_context_from_results(results):
  context_parts=[]

  for i, (doc, meta) in enumerate(zip(
      results['documents'][0],
      results['metadatas'][0]
  )):
      chunk_text=f"[source{i+1}: {meta['subject']}-{meta['topic']}]\n{doc}"

      context_parts.append(chunk_text)

  context_str="\n\n----\n\n".join(context_parts)

  return context_str

context=build_context_from_results(results)
print("Built context string from retrieved chunks:")
print("="*60)
print(context[:500]+"...")
print(f"\nTotal length of context: {len(context)}characters")





#rag generation function
def generate_rag_answer(question, context):
  system_prompt="""
  You are a helpful academic assistant for engineering students.
    You will be given context retrieved from a college knowledge base, and a student's question.
    RULES:
    1. Answer ONLY using the information provided in the context below.
    2. If the answer is not found in the context, say exactly:
       "I don't have enough information in my knowledge base to answer this question."
    3. Do not use your general training knowledge.
    4. Keep answers clear, accurate, and beginner-friendly.
    5. Mention which source the information came from when possible."""
  # USER PROMPT: The context + question formatted as the user message
  user_prompt = f"""Context from Knowledge Base:
{context}
---
Student's Question: {question}
Please answer the question based only on the context provided above."""


  response = groq_Cilent.chat.completions.create(
      model="llama-3.1-8b-instant",
      messages=[
          {"role": "system", "content": system_prompt},
          {"role": "user", "content": user_prompt}
      ],
      temperature=0.1,
      max_tokens=500
  )
  answer=response.choices[0].message.content
  return answer
print("RAG generation function defined.")

#rag pipeline function

def ask_college_assistant(question, top_k=3, verbose=True):
  if verbose:
    print(f"Question: {question}")
    print("="*60)
    print("Step 1: Retroeving relevant documents..")

    results=retrieve_revlevant_chuncks(question, top_k=top_k)

    if verbose:
      print(f"Retrieved {top_k} chunks from the knowledge base:")
      for i, meta in enumerate(results['metadatas'][0]):
        print(f"  {i+1}.{meta['subject']}-{meta['topic']}")
      print("\nStep2: Building context string...")

    context = build_context_from_results(results)

    if verbose:
      print(f"Context build ({len(context)} characters)")
      print("\nStep 3: Sending to LLM for answer generation...")

    answer=generate_rag_answer(question, context)

    if verbose:
      print("\n" + "=" *60)
      print("ANSWER:")
      print("=" * 60)
      print(answer)
      print("=" * 60)

    return answer

  print("Complete RAG pipeline execution.")

question_1='what is the etl and what are its three main stages?'
answer_1=ask_college_assistant(question_1,top_k=3,verbose=True)
print('\nFINAL ANSWER:\n')
print(answer_1)

!pip install langchain langchain-community langchain-groq faiss-cpu sentence-transformers -q

import os
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

# User Inputs
groq_api_key = input("Enter your Groq API Key: ")

platform = input(
    "Select Platform (Instagram/LinkedIn/WhatsApp/Facebook/X): "
)

content_type = input(
    "Content Type (Photo/Video/Reel/Story/Post): "
)

tone = input(
    "Tone (Funny/Motivational/Professional/Sad/Emotional/Custom): "
)

description = input(
    "Describe your photo/video/post: "
)

length = input(
    "Caption Length (Short/Medium/Long): "
)

hashtags = input(
    "Include Hashtags? (Yes/No): "
)

emoji = input(
    "Include Emojis? (Yes/No): "
)

num_captions = input(
    "How many captions do you want? "
)

max_tokens = int(
    input("Maximum Output Tokens (e.g., 500): ")
)

# Set API Key
os.environ["GROQ_API_KEY"] = groq_api_key

# LLM
llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.7,
    max_tokens=max_tokens
)

# Prompt
prompt = PromptTemplate(
    input_variables=[
        "platform",
        "content_type",
        "tone",
        "description",
        "length",
        "hashtags",
        "emoji",
        "num_captions"
    ],
    template="""
You are an expert social media content creator.

Generate {num_captions} DIFFERENT caption options.

User Preferences:
Platform: {platform}
Content Type: {content_type}
Tone: {tone}
Description: {description}
Caption Length: {length}
Include Hashtags: {hashtags}
Include Emojis: {emoji}

Platform Guidelines:
- Instagram → trendy, engaging
- LinkedIn → professional
- WhatsApp → short and impactful
- Facebook → conversational
- X/Twitter → concise and attention-grabbing

Requirements:
1. Every caption must be different.
2. Use the requested tone.
3. Follow the requested length.
4. Include emojis only if requested.
5. Include hashtags only if requested.
6. Number each caption clearly.
7. Make captions creative and high quality.

Output Format:

Caption 1:
...

Caption 2:
...

Caption 3:
...
"""
)

parser = StrOutputParser()

chain = prompt | llm | parser

response = chain.invoke({
    "platform": platform,
    "content_type": content_type,
    "tone": tone,
    "description": description,
    "length": length,
    "hashtags": hashtags,
    "emoji": emoji,
    "num_captions": num_captions
})

print("\n" + "=" * 60)
print("GENERATED CAPTIONS")
print("=" * 60)
print(response)